### ISSUE TITLE
Chef Supermarket

### ISSUE THREAD

**Issue by kwilczynski** [hectcastro/chef-collectd#45]
Hello,

This cookbook is very nice, thank you for picking up the slack after where the https://github.com/coderanger/chef-collectd active development has stopped, and putting the time to maintain it.

Would you consider publishing it on Chef Supermarket (if possible, of course)? It would delight more people and bring more users willing to help with development.

Let me know what do you think about the idea.

Thank you in advance!

**Comment by trahma** [comment]
+1 on this.  I found this after being frustrated with the existing supermarket collectd cookbook

**Comment by hectcastro** [comment]
Going to look into this over the weekend. I haven't really kept up with all of the Chef ecosystem changes, so I need to figure out what the requirements are for getting a new project up on the Supermarket. One appears to be a private key tied to my Chef identity, but I haven't found an easy place to generate one.

**Comment by hectcastro** [comment]
I got the key situation sorted out. The next step is determining if there is a convention for uploading multiple cookbooks of the same type, or if we should start a discussion with the current `collectd` cookbook maintainer.

Anyone know if there is an existing convention for uploading multiple cookbooks of the same type?

**Comment by kwilczynski** [comment]
@hectcastro thank you for your time and that you looked into this! Often, when similar cookbook appears on he Supermarket, people tend to just re-name it slightly, sometimes the name would end up being for example `collectd-ng`, etc., sometimes it would be `collectd2`, or `collectd-new` ... In some cases, you can ask Supermarket administrator to replace old cookbook with your version if the old one is completely not maintained (but I have not seen this happening too often, to be honest).

**Comment by hectcastro** [comment]
I uploaded the [`feature/hmc/chef-supermarket`](https://github.com/hectcastro/chef-collectd/tree/feature/hmc/chef-supermarket) branch of this cookbook to the Chef Supermarket as [`collectd-ng`](https://supermarket.chef.io/cookbooks/collectd-ng) for testing. Not going to merge the changes yet because I suspect it is going to cause problems for those referencing this cookbook as `collectd`.

Once we confirm everything works well on the Chef Supermarket, I'll plan on cutting a 2.0.0 release to signal backward incompatibility because of the cookbook name change.
